# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.TextField(default='direccion', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('f', 'femenino'), ('m', 'masculino')], max_length=10),
        ),
    ]
